name: Manually sync docker image from docker.io to Aliyun

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '镜像名称'
        required: true
        default: ''
      image_version:
        description: '版本'
        required: true
        default: 'latest'
      namespace:
        description: '命名空间'
        required: true
        type: choice
        options:
          - wheny
          - baoor
        default: 'wheny'
jobs:
  sync:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Login to Aliyun Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        
      - name: Sync docker images
        env:
          REGISTRY: registry.cn-hangzhou.aliyuncs.com
          NAMESPACE: ${{ github.event.inputs.namespace }}
          IMAGENAME: ${{ github.event.inputs.image_name }}
          IMAGEVERSION: $"{{ github.event.inputs.image_version }}"
        run: |
          chmod +x manually_sync_images.sh
          ./manually_sync_images.sh
        
