name: Manually sync docker image from docker.io to Aliyun

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '镜像名称'
        required: true
        default: ''
      image_version:
        description: '版本'
        required: true
        default: 'latest'
      namespace:
        description: '命名空间'
        required: true
        type: choice
        options:
          - wheny
          - baoor
        default: 'wheny'
      my_image_name:
        description: '我的镜像名称'
        required: true
        default: ''
jobs:
  sync:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Login to Aliyun Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        
      - name: Sync docker images
        env:          
          IMAGENAME: ${{ github.event.inputs.image_name }}
          IMAGEVERSION: ${{ github.event.inputs.image_version }}
          REGISTRY: ${{ vars.REGISTRY }}
          NAMESPACE: ${{ github.event.inputs.namespace }}
          MYIMAGENAME: ${{ github.event.inputs.my_image_name }}
        run: |
          docker pull "${IMAGENAME}:${IMAGEVERSION}"
          docker tag "${IMAGENAME}:${IMAGEVERSION}" "${REGISTRY}/${NAMESPACE}/${MYIMAGENAME}:${IMAGEVERSION}"
          docker push "${REGISTRY}/${NAMESPACE}/${MYIMAGENAME}:${IMAGEVERSION}"

        
