name: Sync docker image from docker.io to Aliyun

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Login to Aliyun Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        
      - name: Sync docker images
        run: |
          chmod +x sync_images.sh
          ./sync_images.sh
        env:
          REGISTRY: ${{ vars.REGISTRY }}
        
