name: Sync docker image from docker.io to Aliyun

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Aliyun registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        
      - name: Sync docker images
        run: |
          chmod +x sync_docker_mirror.sh
          ./sync_docker_mirror.sh
        env:
          REGISTRY: ${{ vars.REGISTRY }}
        
